### ISSUE TITLE
Consider moving to GitHub Actrion

### ISSUE THREAD

**Issue by peter279k** [mercari/dietcube#34]
As title, the Travis CI dot org will be deprecated soon and the Travis CI dot com is not friendly for the open source project.

And I think we can consider moving to the GitHub Action.

**Comment by DQNEO** [comment]
Agree. Could you make a PR ?

**Comment by peter279k** [comment]
Thanks for your reply. I will do that.

**Comment by DQNEO** [comment]
After a discussion with @HaiTo , we have decided that we archive this repository.
So let me close this.
Thanks anyway!
